### PR TITLE
Upgrades Timex to 1.0 and relaxes elixir version

### PR DESCRIPTION
**Pull request by anshul**

### CODE REVIEW

**Comment by benlangfeld** [comment]
Thanks! Would you please re-submit this against the upstream repository? https://github.com/adhearsion/mojo-auth.ex

**Comment by anshul** [comment]
Sure.

**Comment by anshul** [comment]
Upstream appears to have this already fixed.  Can you release it to hex?

**Comment by benlangfeld** [comment]
1.0.2 is released. Try taking it for a spin.

**Pull request closed without merging**
